### ISSUE TITLE
Aprovisionar la máquina virtual de AWS con Ansible, configurándola para usar Node.js

### ISSUE THREAD

**Issue by NestorsImagination** [NestorsImagination/Sample-Multiplayer-Shooter#13]

**Comment by jmanday** [comment]
He probado el provisionamiento con ansible en una de mis máquinas en AWS y funciona correctamente.

![](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito2/prueba_prov_comp.png)
