### ISSUE TITLE
Añadir al Hito 2 el provisionamiento con Chef.

### ISSUE THREAD

**Issue by NestorsImagination** [NestorsImagination/Sample-Multiplayer-Shooter#14]

**Comment by JPPorcel** [comment]
He probado tu provisionamiento con Chef y va perfectamente. Testeado sobre una máquina Ubuntu Server 16.04 (64 bit) en AWS y Chef v12.15.19.

![Prueba chef](https://github.com/JPPorcel/Proyecto-Elliot/blob/gh-pages/images/prueba_chef.png?raw=true)
