### ISSUE TITLE
Modificar el archivo Playbook de Ansible para adaptarlo para su uso en la última versión

### ISSUE THREAD

**Issue by NestorsImagination** [NestorsImagination/Sample-Multiplayer-Shooter#19]
Tal como está sólo funciona en versiones antiguas.

**Comment by JPPorcel** [comment]
Tras probar la versión anterior del playbook de ansible pude comprobar que no funcionaba en mi máquina ya que mi versión de Ansible era superior y el formato del playbook variaba.

Con esta nueva versión del playbook me funciona perfectamente el provisionamiento con Ansible v2.2.0.0. Testeado sobre una máquina Ubuntu Server 16.04 (64 bit) en AWS.

![Prueba ansible](https://github.com/JPPorcel/Proyecto-Elliot/blob/gh-pages/images/prueba_ansible.png?raw=true)
