### ISSUE TITLE
Implementar el provisionamiento con Vagrant para AWS

### ISSUE THREAD

**Issue by NestorsImagination** [NestorsImagination/Sample-Multiplayer-Shooter#23]

**Comment by JPPorcel** [comment]
He probado tu orquestación y provisionamiento con Vagrant en AWS y funciona correctamente.

![vagrant1](https://github.com/JPPorcel/Proyecto-Elliot/blob/gh-pages/images/vagrantDani1.png?raw=true)

![vagrant1](https://github.com/JPPorcel/Proyecto-Elliot/blob/gh-pages/images/vagrantDani2.png?raw=true)

![vagrant1](https://github.com/JPPorcel/Proyecto-Elliot/blob/gh-pages/images/awsDani.png?raw=true)
