### ISSUE TITLE
Archivos necesarios para la creación de un entorno de pruebas con Docker y Vagrant

### ISSUE THREAD

**Issue by NestorsImagination** [NestorsImagination/Sample-Multiplayer-Shooter#25]

**Comment by jmanday** [comment]
Corregido el hito del compañero como se puede ver en la supervisión de este issue

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img17.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img18.png)

**Comment by NestorsImagination** [comment]
> Corregido el hito del compañero como se puede ver en la supervisión de este issue

Gracias, pero te ha faltado la segunda parte, que es lo importante (has creado la máquina, pero lo importante es crear los contenedores en la máquina con `vagrant -n"número de mundos de juego" up --provider=docker`)

**Comment by jmanday** [comment]
Cierto, se me olvidaron ponerlas, aquí muestro la creación del contenedor y la prueba de que todo funciona desde mi máquina hacia la de Amazon.

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img26.png)

![alt text](https://raw.githubusercontent.com/jmanday/Images/master/CRUT/Hito4/h4-img27.png)
